CREATE TABLE [Game].[Armor]
(
	[EquipmentId] TINYINT NOT NULL PRIMARY KEY, 
	[Defense] TINYINT NOT NULL DEFAULT 0,
	[Evade] TINYINT NOT NULL DEFAULT 0,
	[MagicDefense] TINYINT NOT NULL DEFAULT 0,
	[MagicEvade] TINYINT NOT NULL DEFAULT 0,
)
